postsList:
    path: /posts
    controller: App\Controller\PostController::list
    methods: get

postDetails:
    path: /posts/{id}
    controller: App\Controller\PostController::details
    methods: get

postCreate:
    path: /posts
    controller: App\Controller\PostController::create
    methods: post

postUpdate:
    path: /posts/{id}
    controller: App\Controller\PostController::update
    methods: put

postDelete:
    path: /posts/{id}
    controller: App\Controller\PostController::delete
    methods: delete

commentsList:
    path: /comments
    controller: App\Controller\CommentController::list
    methods: get

commentDetails:
    path: /comments/{id}
    controller: App\Controller\CommentController::details
    methods: get

commentCreate:
    path: /comments
    controller: App\Controller\CommentController::create
    methods: post

commentUpdate:
    path: /comments/{id}
    controller: App\Controller\CommentController::update
    methods: put

commentDelete:
    path: /comments/{id}
    controller: App\Controller\CommentController::delete
    methods: delete
